"use client";

import Image from "next/image";

import { MotionDiv } from "@/components/motion-elements";
import { cn } from "@/lib/utils";

const galleryImages = [
  {
    src: "/images/image-13.png",
    alt: "UrbanIQ valuation insight – AI assisted market analysis",
    span: "col-span-2 row-span-2"
  },
  {
    src: "/images/image-14.png",
    alt: "UrbanIQ legal risk detection – property documentation signals",
    span: "col-span-2 row-span-2"
  },
  {
    src: "/images/image-15.jpg",
    alt: "UrbanIQ property intelligence – zoning and urban context",
    span: "md:col-span-1 col-span-2 row-span-2"
  },
  {
    src: "/images/image-16.jpg",
    alt: "UrbanIQ AI dashboard – asset health indicators",
    span: "md:col-span-1 col-span-2 row-span-2"
  },
  {
    src: "/images/image-17.png",
    alt: "UrbanIQ valuation comparison – confidence range output",
    span: "col-span-2 row-span-2"
  },
  {
    src: "/images/image-18.png",
    alt: "UrbanIQ market demand signals – AI enriched data",
    span: "col-span-2 row-span-2"
  },
  {
    src: "/images/image-19.png",
    alt: "UrbanIQ legal & registry insights – automated checks",
    span: "col-span-2 row-span-2"
  },
  {
    src: "/images/image-20.png",
    alt: "UrbanIQ decision intelligence – next best action",
    span: "col-span-2 row-span-2"
  },
  {
    src: "/images/image-21.png",
    alt: "UrbanIQ property intelligence overview",
    span: "md:col-span-1 col-span-2 row-span-2"
  }
];

export default function Gallery() {
  return (
    <section id="gallery" className="py-14 md:py-20">
      <div className="container mx-auto max-w-7xl">
        <MotionDiv
          viewport={{ once: true }}
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: "easeOut" }}
          className="mx-auto max-w-4xl space-y-3 pb-12 text-center md:pb-16"
        >
          <h3 className="text-3xl font-bold sm:text-4xl">
            Real Intelligence. Real Assets.
          </h3>

          <p className="text-muted-foreground">
            Visual outputs generated by UrbanIQ to assess property value,
            legal risk and sale readiness using AI-assisted real estate data.
          </p>
        </MotionDiv>

        <div className="grid auto-rows-[200px] grid-cols-2 gap-4 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-5">
          {galleryImages.map((image, index) => (
            <MotionDiv
              key={index}
              viewport={{ once: true }}
              initial={{ opacity: 0, scale: 0.9, filter: "blur(6px)" }}
              whileInView={{ opacity: 1, scale: 1, filter: "blur(0px)" }}
              transition={{
                duration: 0.4,
                ease: "easeOut",
                delay: index * 0.05
              }}
              className={cn(
                "relative overflow-hidden rounded-2xl",
                image.span
              )}
            >
              <Image
                fill
                src={image.src}
                alt={image.alt}
                className="object-cover transition-transform duration-300 hover:scale-105"
                sizes="(max-width: 640px) 50vw, (max-width: 768px) 33vw, (max-width: 1024px) 25vw, 20vw"
              />
            </MotionDiv>
          ))}
        </div>
      </div>
    </section>
  );
}